[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
[[headers]]
for = "/img/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
for = "/css/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000"
